import React, { useState, useEffect } from 'react';
import PropTypes from 'prop-types';
import { Card, CardContent, Typography, TextField, Button } from '@mui/material';
import { fetchGeoLocation, fetchWeatherData } from '../../api/weatherAPI';
import { formateName } from '../../utils';
import LocationCard from '../locationCard';
import Autocomplete from '@mui/material/Autocomplete';
import CircularProgress from '@mui/material/CircularProgress';

const LocationSearch = ({ title }) => {
  const [location, setLocation] = useState({});
  const [weatherData, setWeatherData] = useState([]);
  const [error, setError] = useState('');
  const [open, setOpen] = React.useState(false);
  const [options, setOptions] = React.useState([]);
  const [fetchingData, setFetchingData] = useState(false); // New state for fetching data
  const maxHours = 48;


    
  const fetchLocations = async (location) => {
    try {
      setFetchingData(true); // Start fetching data
      const data = (await fetchGeoLocation(location)).results;
      return data;
    } catch (error) {
      throw new Error('An error occurred while fetching geo location data.');
    } finally { 
        setFetchingData(false); // Stop fetching data
    }
  };

  const fetchWeather = async (coords) => {
    try {
      setFetchingData(true); // Start fetching data
      const data = await fetchWeatherData(coords.latitude, coords.longitude, coords.timezone);
      setOptions([]);
      const currentTime = new Date();
      let hourlyData = [];
      for (let i = 0; i < maxHours; i++) {
        let currentDate =
          currentTime.getDate() === parseInt(data.hourly.time[i].substring(8, 10)) &&
          currentTime.toTimeString().substring(0, 2) === data.hourly.time[i].substring(11, 13);
        hourlyData.push({
          time: new Date(data.hourly.time[i]),
          temperature: data.hourly.temperature_2m[i],
          description: data.hourly.weathercode[i],
          precipitationProbability: data.hourly.precipitation_probability[i],
          isCurrent: currentDate,
        });
      }
      data.hourly = hourlyData;
      let dailyData = [];
        for (let i = 0; i < data.daily.time.length; i++) {
            dailyData.push({
                time: new Date(data.daily.time[i]),
                temperature_2m_max: data.daily.temperature_2m_max[i],
                temperature_2m_min: data.daily.temperature_2m_min[i],
                description: data.daily.weathercode[i],
                sunrise: new Date(data.daily.sunrise[i]),
                sunset: new Date(data.daily.sunset[i]),
                precipitationProbability: data.daily.precipitation_probability_max[i],
            });
        }
        data.daily = dailyData;
      const newData = { coords: coords, data };
      setWeatherData([newData, ...weatherData]);

      
      setError('');
    } catch (error) {
      setWeatherData([]);
      setError(error.message);
    } finally {
      setFetchingData(false); // Stop fetching data
    }
  };

  const handleTextFieldChange = async (event) => {
    let data = await fetchLocations(event.target.value);
    if (data) {
      setOptions(data);
    } else {
      setOptions([]);
    }
  };

  const handleSearch = async (event) => {
    if (event.target.value) {
      const searchObject = (await fetchLocations(event.target.value))[0];
      fetchWeather(searchObject);
    }
  };

  const handleAutocompleteChange = (event, value) => {
    if (value) {
      setLocation(value);
      fetchWeather(value);
    }
  };

  return (
    <Card variant="outlined" sx={{ margin: '2%' }}>
      <CardContent>
        <Typography variant="h4" component="h1" align="center" gutterBottom>
          {title}
        </Typography>

        <Autocomplete
          onChange={handleAutocompleteChange}
          sx={{ width: '100%' }}
          open={open}
          onOpen={() => {
            setOpen(true);
          }}
          onClose={() => {
            setOpen(false);
          }}
          isOptionEqualToValue={(option, value) => option.name === value.name}
          getOptionLabel={(option) => formateName(option)}
          options={options}
          loading={fetchingData} // Use the fetchingData state as the loading value
          renderInput={(params) => (
            <TextField
              {...params}
              label="Search Location"
              onChange={handleTextFieldChange}
              onKeyPress={(event) => {
                if (event.key === 'Enter') {
                  handleSearch(event);
                }
              }}
              InputProps={{
                ...params.InputProps,
                endAdornment: (
                  <React.Fragment>
                    {fetchingData ? <CircularProgress color="inherit" size={20} /> : null}
                    {params.InputProps.endAdornment}
                  </React.Fragment>
                ),
              }}
              fullWidth
            />
          )}
        />
      </CardContent>
      {error && (
        <Typography variant="body1" color="error" sx={{ marginTop: '1rem' }}>
          {error}
        </Typography>
      )}
      {weatherData.map((data, index) => (
        <div key={index} style={{ marginTop: '1rem' }}>
          <LocationCard weatherObject={data} />
        </div>
      ))}
    </Card>
  );
};

LocationSearch.propTypes = {
  title: PropTypes.string.isRequired,
};

export default LocationSearch;

const MockData = {
        coords: {
                "id": 2960992,
                "name": "Waterford",
                "latitude": 52.25833,
                "longitude": -7.11194,
                "elevation": 10,
                "feature_code": "PPLA2",
                "country_code": "IE",
                "admin1_id": 7521315,
                "admin2_id": 11611446,
                "timezone": "Europe/Dublin",
                "population": 47904,
                "country_id": 2963597,
                "country": "Ireland",
                "admin1": "Munster",
                "admin2": "Waterford"
              },
              data:{
                
                    "latitude": 52.26,
                    "longitude": -7.11,
                    "generationtime_ms": 1.1799335479736328,
                    "utc_offset_seconds": 3600,
                    "timezone": "Europe/London",
                    "timezone_abbreviation": "BST",
                    "elevation": 18,
                    "hourly_units": {
                      "time": "iso8601",
                      "temperature_2m": "°C",
                      "relativehumidity_2m": "%",
                      "apparent_temperature": "°C",
                      "precipitation_probability": "%",
                      "weathercode": "wmo code"
                    },
                    "hourly": {
                      "time": [
                        "2023-06-03T00:00",
                        "2023-06-03T01:00",
                        "2023-06-03T02:00",
                        "2023-06-03T03:00",
                        "2023-06-03T04:00",
                        "2023-06-03T05:00",
                        "2023-06-03T06:00",
                        "2023-06-03T07:00",
                        "2023-06-03T08:00",
                        "2023-06-03T09:00",
                        "2023-06-03T10:00",
                        "2023-06-03T11:00",
                        "2023-06-03T12:00",
                        "2023-06-03T13:00",
                        "2023-06-03T14:00",
                        "2023-06-03T15:00",
                        "2023-06-03T16:00",
                        "2023-06-03T17:00",
                        "2023-06-03T18:00",
                        "2023-06-03T19:00",
                        "2023-06-03T20:00",
                        "2023-06-03T21:00",
                        "2023-06-03T22:00",
                        "2023-06-03T23:00",
                        "2023-06-04T00:00",
                        "2023-06-04T01:00",
                        "2023-06-04T02:00",
                        "2023-06-04T03:00",
                        "2023-06-04T04:00",
                        "2023-06-04T05:00",
                        "2023-06-04T06:00",
                        "2023-06-04T07:00",
                        "2023-06-04T08:00",
                        "2023-06-04T09:00",
                        "2023-06-04T10:00",
                        "2023-06-04T11:00",
                        "2023-06-04T12:00",
                        "2023-06-04T13:00",
                        "2023-06-04T14:00",
                        "2023-06-04T15:00",
                        "2023-06-04T16:00",
                        "2023-06-04T17:00",
                        "2023-06-04T18:00",
                        "2023-06-04T19:00",
                        "2023-06-04T20:00",
                        "2023-06-04T21:00",
                        "2023-06-04T22:00",
                        "2023-06-04T23:00",
                        "2023-06-05T00:00",
                        "2023-06-05T01:00",
                        "2023-06-05T02:00",
                        "2023-06-05T03:00",
                        "2023-06-05T04:00",
                        "2023-06-05T05:00",
                        "2023-06-05T06:00",
                        "2023-06-05T07:00",
                        "2023-06-05T08:00",
                        "2023-06-05T09:00",
                        "2023-06-05T10:00",
                        "2023-06-05T11:00",
                        "2023-06-05T12:00",
                        "2023-06-05T13:00",
                        "2023-06-05T14:00",
                        "2023-06-05T15:00",
                        "2023-06-05T16:00",
                        "2023-06-05T17:00",
                        "2023-06-05T18:00",
                        "2023-06-05T19:00",
                        "2023-06-05T20:00",
                        "2023-06-05T21:00",
                        "2023-06-05T22:00",
                        "2023-06-05T23:00",
                        "2023-06-06T00:00",
                        "2023-06-06T01:00",
                        "2023-06-06T02:00",
                        "2023-06-06T03:00",
                        "2023-06-06T04:00",
                        "2023-06-06T05:00",
                        "2023-06-06T06:00",
                        "2023-06-06T07:00",
                        "2023-06-06T08:00",
                        "2023-06-06T09:00",
                        "2023-06-06T10:00",
                        "2023-06-06T11:00",
                        "2023-06-06T12:00",
                        "2023-06-06T13:00",
                        "2023-06-06T14:00",
                        "2023-06-06T15:00",
                        "2023-06-06T16:00",
                        "2023-06-06T17:00",
                        "2023-06-06T18:00",
                        "2023-06-06T19:00",
                        "2023-06-06T20:00",
                        "2023-06-06T21:00",
                        "2023-06-06T22:00",
                        "2023-06-06T23:00",
                        "2023-06-07T00:00",
                        "2023-06-07T01:00",
                        "2023-06-07T02:00",
                        "2023-06-07T03:00",
                        "2023-06-07T04:00",
                        "2023-06-07T05:00",
                        "2023-06-07T06:00",
                        "2023-06-07T07:00",
                        "2023-06-07T08:00",
                        "2023-06-07T09:00",
                        "2023-06-07T10:00",
                        "2023-06-07T11:00",
                        "2023-06-07T12:00",
                        "2023-06-07T13:00",
                        "2023-06-07T14:00",
                        "2023-06-07T15:00",
                        "2023-06-07T16:00",
                        "2023-06-07T17:00",
                        "2023-06-07T18:00",
                        "2023-06-07T19:00",
                        "2023-06-07T20:00",
                        "2023-06-07T21:00",
                        "2023-06-07T22:00",
                        "2023-06-07T23:00",
                        "2023-06-08T00:00",
                        "2023-06-08T01:00",
                        "2023-06-08T02:00",
                        "2023-06-08T03:00",
                        "2023-06-08T04:00",
                        "2023-06-08T05:00",
                        "2023-06-08T06:00",
                        "2023-06-08T07:00",
                        "2023-06-08T08:00",
                        "2023-06-08T09:00",
                        "2023-06-08T10:00",
                        "2023-06-08T11:00",
                        "2023-06-08T12:00",
                        "2023-06-08T13:00",
                        "2023-06-08T14:00",
                        "2023-06-08T15:00",
                        "2023-06-08T16:00",
                        "2023-06-08T17:00",
                        "2023-06-08T18:00",
                        "2023-06-08T19:00",
                        "2023-06-08T20:00",
                        "2023-06-08T21:00",
                        "2023-06-08T22:00",
                        "2023-06-08T23:00",
                        "2023-06-09T00:00",
                        "2023-06-09T01:00",
                        "2023-06-09T02:00",
                        "2023-06-09T03:00",
                        "2023-06-09T04:00",
                        "2023-06-09T05:00",
                        "2023-06-09T06:00",
                        "2023-06-09T07:00",
                        "2023-06-09T08:00",
                        "2023-06-09T09:00",
                        "2023-06-09T10:00",
                        "2023-06-09T11:00",
                        "2023-06-09T12:00",
                        "2023-06-09T13:00",
                        "2023-06-09T14:00",
                        "2023-06-09T15:00",
                        "2023-06-09T16:00",
                        "2023-06-09T17:00",
                        "2023-06-09T18:00",
                        "2023-06-09T19:00",
                        "2023-06-09T20:00",
                        "2023-06-09T21:00",
                        "2023-06-09T22:00",
                        "2023-06-09T23:00"
                      ],
                      "temperature_2m": [
                        13.2,
                        11.7,
                        11.2,
                        10.9,
                        10.5,
                        10.6,
                        10,
                        11.8,
                        14,
                        16,
                        17.7,
                        19,
                        20.4,
                        20.5,
                        20.6,
                        20.5,
                        20.8,
                        20.8,
                        21.5,
                        20.4,
                        19.1,
                        17.8,
                        16.4,
                        15,
                        13.7,
                        12.8,
                        11.7,
                        11.2,
                        12.5,
                        10.4,
                        10.8,
                        13,
                        15.3,
                        17,
                        18.6,
                        19.8,
                        20.4,
                        20.9,
                        21.4,
                        21.5,
                        21.9,
                        22,
                        22.1,
                        22,
                        18.4,
                        17.2,
                        15.5,
                        14.2,
                        13.5,
                        13,
                        12.8,
                        12.7,
                        12.7,
                        12.6,
                        12.5,
                        13.3,
                        14.7,
                        16.5,
                        18,
                        19.3,
                        20.6,
                        21.4,
                        21.7,
                        21.6,
                        21.4,
                        21.2,
                        20.8,
                        20.2,
                        19.4,
                        18.2,
                        16.8,
                        15.7,
                        15,
                        14.5,
                        14.2,
                        14,
                        13.6,
                        13.1,
                        12.9,
                        13.4,
                        14.6,
                        16.2,
                        17.6,
                        18.9,
                        20.2,
                        20.9,
                        21,
                        21.5,
                        21.5,
                        21,
                        20.5,
                        19.7,
                        18.9,
                        17.8,
                        16.4,
                        15.2,
                        14.6,
                        14.2,
                        13.9,
                        13.6,
                        13.3,
                        13.1,
                        13,
                        13.5,
                        13.5,
                        16.5,
                        18.8,
                        19.8,
                        20,
                        20.1,
                        20.2,
                        20,
                        19.8,
                        19.7,
                        19.5,
                        19,
                        17.8,
                        16.4,
                        15,
                        14,
                        13.1,
                        12.5,
                        12,
                        11.7,
                        11.7,
                        12,
                        12.5,
                        13.2,
                        14.1,
                        15.1,
                        16,
                        16.9,
                        17.7,
                        18.5,
                        19.3,
                        20,
                        20.4,
                        20.3,
                        20,
                        19.5,
                        18.9,
                        18.3,
                        17.8,
                        17.5,
                        17.3,
                        17.1,
                        16.8,
                        16.6,
                        16.3,
                        16,
                        15.6,
                        15.5,
                        15.8,
                        16.4,
                        17.1,
                        17.9,
                        18.8,
                        19.6,
                        20.3,
                        20.9,
                        21.3,
                        21.5,
                        21.5,
                        21.2,
                        20.5,
                        19.6,
                        18.8,
                        18.4
                      ],
                      "relativehumidity_2m": [
                        66,
                        71,
                        73,
                        72,
                        72,
                        71,
                        74,
                        71,
                        68,
                        63,
                        52,
                        49,
                        44,
                        48,
                        46,
                        44,
                        43,
                        42,
                        23,
                        23,
                        23,
                        27,
                        29,
                        32,
                        36,
                        39,
                        42,
                        44,
                        49,
                        53,
                        59,
                        65,
                        64,
                        62,
                        59,
                        52,
                        48,
                        47,
                        46,
                        45,
                        41,
                        40,
                        40,
                        29,
                        41,
                        43,
                        42,
                        44,
                        42,
                        38,
                        42,
                        48,
                        53,
                        60,
                        67,
                        71,
                        70,
                        64,
                        59,
                        57,
                        53,
                        49,
                        46,
                        43,
                        42,
                        41,
                        41,
                        42,
                        44,
                        47,
                        51,
                        58,
                        61,
                        62,
                        64,
                        68,
                        72,
                        74,
                        76,
                        76,
                        72,
                        64,
                        55,
                        53,
                        51,
                        50,
                        51,
                        48,
                        47,
                        46,
                        44,
                        44,
                        45,
                        48,
                        53,
                        59,
                        63,
                        64,
                        65,
                        68,
                        71,
                        73,
                        76,
                        77,
                        83,
                        75,
                        69,
                        65,
                        63,
                        60,
                        56,
                        52,
                        49,
                        47,
                        47,
                        49,
                        55,
                        62,
                        69,
                        73,
                        76,
                        79,
                        82,
                        85,
                        87,
                        87,
                        85,
                        82,
                        78,
                        73,
                        68,
                        63,
                        57,
                        53,
                        51,
                        49,
                        49,
                        49,
                        50,
                        52,
                        54,
                        57,
                        60,
                        63,
                        67,
                        70,
                        72,
                        74,
                        75,
                        76,
                        77,
                        77,
                        74,
                        69,
                        65,
                        62,
                        61,
                        59,
                        58,
                        57,
                        56,
                        56,
                        57,
                        58,
                        60,
                        63,
                        66,
                        68
                      ],
                      "apparent_temperature": [
                        11.7,
                        10.1,
                        9.4,
                        9,
                        8.6,
                        8.8,
                        8.4,
                        10.4,
                        12.7,
                        14.8,
                        16.2,
                        17.7,
                        18.6,
                        18.6,
                        18.6,
                        18.1,
                        18.4,
                        18.4,
                        16.9,
                        16,
                        15.3,
                        14.5,
                        13,
                        11.7,
                        10.8,
                        9.9,
                        8.6,
                        8,
                        9.8,
                        7.5,
                        8.5,
                        11.5,
                        13.7,
                        15.4,
                        17.5,
                        18.2,
                        18.6,
                        19.2,
                        19.6,
                        19.5,
                        19.8,
                        20,
                        20.5,
                        18.7,
                        15.2,
                        14.2,
                        12.6,
                        11.2,
                        9.8,
                        8.9,
                        8.7,
                        8.9,
                        9.1,
                        9.2,
                        9.7,
                        10.9,
                        12.6,
                        14.5,
                        16.5,
                        18.9,
                        20.2,
                        20.7,
                        20.5,
                        19.9,
                        19.5,
                        18.8,
                        17.8,
                        17,
                        16.2,
                        15.1,
                        14.1,
                        13.1,
                        12.4,
                        11.6,
                        10.8,
                        10.9,
                        11.1,
                        10.7,
                        10.6,
                        11.3,
                        12.8,
                        14.5,
                        16,
                        18.2,
                        19.5,
                        20.1,
                        20.4,
                        20.6,
                        19.9,
                        18.5,
                        17.2,
                        16.3,
                        15.8,
                        15,
                        14,
                        13,
                        12.2,
                        11.6,
                        11.4,
                        11,
                        10.6,
                        10.5,
                        10.6,
                        11.3,
                        12.9,
                        15.6,
                        17.7,
                        18.9,
                        19.4,
                        19.5,
                        19.2,
                        18.6,
                        17.8,
                        17,
                        16.3,
                        16.1,
                        15.6,
                        14.9,
                        14,
                        13,
                        11.9,
                        11.1,
                        10.7,
                        10.5,
                        10.5,
                        10.7,
                        11.1,
                        11.6,
                        12,
                        12.4,
                        12.8,
                        13.4,
                        14.2,
                        15.1,
                        16,
                        16.6,
                        16.8,
                        16.5,
                        16.3,
                        16.2,
                        15.9,
                        15.6,
                        15.4,
                        15.4,
                        15.6,
                        15.6,
                        15.4,
                        15.1,
                        14.8,
                        14.4,
                        14,
                        13.7,
                        13.6,
                        13.7,
                        14,
                        14.6,
                        15.6,
                        16.4,
                        17.3,
                        18.3,
                        18.8,
                        19,
                        19.2,
                        19.4,
                        19,
                        18.5,
                        18,
                        17.7
                      ],
                      "precipitation_probability": [
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        2,
                        4,
                        6,
                        4,
                        2,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        1,
                        2,
                        3,
                        2,
                        1,
                        0,
                        0,
                        0,
                        0,
                        2,
                        4,
                        6,
                        8,
                        11,
                        13,
                        12,
                        11,
                        10,
                        9,
                        7,
                        6,
                        6,
                        6,
                        6,
                        8,
                        11,
                        13,
                        12,
                        11,
                        10,
                        8,
                        5,
                        3,
                        3
                      ],
                      "weathercode": [
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        1,
                        1,
                        1,
                        1,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        1,
                        1,
                        1,
                        1,
                        1,
                        1,
                        3,
                        3,
                        3,
                        1,
                        1,
                        1,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        2,
                        2,
                        2,
                        3,
                        3,
                        3,
                        3,
                        3,
                        3,
                        3,
                        3,
                        3,
                        3,
                        3,
                        3,
                        3,
                        3,
                        3,
                        3,
                        3,
                        3,
                        3,
                        3,
                        3,
                        3,
                        3,
                        3,
                        3,
                        3,
                        3,
                        3,
                        3,
                        3,
                        3,
                        3,
                        3,
                        3,
                        3,
                        3,
                        3,
                        3,
                        3,
                        3,
                        3,
                        3,
                        3
                      ]
                    },
                    "daily_units": {
                      "time": "iso8601",
                      "weathercode": "wmo code",
                      "temperature_2m_max": "°C",
                      "temperature_2m_min": "°C",
                      "sunrise": "iso8601",
                      "sunset": "iso8601"
                    },
                    "daily": {
                      "time": [
                        "2023-06-03",
                        "2023-06-04",
                        "2023-06-05",
                        "2023-06-06",
                        "2023-06-07",
                        "2023-06-08",
                        "2023-06-09"
                      ],
                      "weathercode": [
                        0,
                        0,
                        0,
                        1,
                        3,
                        3,
                        3
                      ],
                      "temperature_2m_max": [
                        21.5,
                        22.1,
                        21.7,
                        21.5,
                        20.2,
                        20.4,
                        21.5
                      ],
                      "temperature_2m_min": [
                        10,
                        10.4,
                        12.5,
                        12.9,
                        13,
                        11.7,
                        15.5
                      ],
                      "sunrise": [
                        "2023-06-03T05:09",
                        "2023-06-04T05:08",
                        "2023-06-05T05:07",
                        "2023-06-06T05:07",
                        "2023-06-07T05:06",
                        "2023-06-08T05:06",
                        "2023-06-09T05:05"
                      ],
                      "sunset": [
                        "2023-06-03T21:43",
                        "2023-06-04T21:44",
                        "2023-06-05T21:45",
                        "2023-06-06T21:46",
                        "2023-06-07T21:47",
                        "2023-06-08T21:48",
                        "2023-06-09T21:49"
                      ]
                    }
                  }
              }
        